apiVersion: extensions/v1beta1
kind: Ingress
metadata:
   namespace: home-dev
   name: home-dev-ingress
   annotations:
     ingress.kubernetes.io/proxy-body-size: "50m"
spec:
   rules:
   - host: "api.sample.com"
     http:
      paths:
      - path: /
        backend:
          serviceName: hello-world-svc
          servicePort: 8080 