---
apiVersion: v1
kind: Service
metadata:
  namespace: {{sse_namespace}}
  name: uc-admin-wfe
  labels:
    run: uc-admin-wfe
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: uc-admin-wfe