---
apiVersion: v1
kind: Service
metadata:
  namespace: "home-dev"
  name: hello-world-svc
  labels:
    run: hello-world-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: hello-world-svc